### ISSUE TITLE
Rails public/assets folder is not created

### ISSUE THREAD

**Issue by josephmo** [rails/sprockets#755] opened 2022-08-09 17:16 UTC
### Expected behavior

Up until this morning, I have been using the following build script to start my Production server:

    sudo rm -Rf /home/deploy/current/
    git clone -b xxxx git@xxxxxxx.git /home/deploy/current
    cd /home/deploy/current/
    bundle update
    bundle install
    rake db:migrate
    rake db:seed
    rails tailwindcss:build
    bundle exec rake assets:precompile
    bundle binstubs puma
    sudo systemctl stop puma
    sudo systemctl start puma
    sudo service nginx restart

and things were working fine. This morning, when I did this, I discovered that the public/assets folder was not created. So, obviously the application is not working.

I rebooted the server, and re-tried this multiple times. No error are generated in the log file. I tried precompiling with the --trace switch, and no errors.

### Actual behavior

See above

### System configuration

- Sprockets version: sprockets-rails - sprockets (4.1.1)
- Ruby version: 3.1.0
- Rails 7.0.3.1

### Example App (Reproduction) - THIS IS IMPORTANT YOUR ISSUE LIKELY WILL NOT BE RESOLVED WITHOUT THIS

The application is proprietary and cannot be posted to a public github location.

**Comment by rafaelfranca** [comment] 2022-08-10 17:25
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. 
Duplicate of #45799

**Closed by rafaelfranca** 2022-08-10 17:25 UTC
