### ISSUE TITLE
Sprockets inserts extra newlines when loading javascript asset

### ISSUE THREAD

**Issue by mulvaney** [rails/sprockets#291] opened 2016-04-29 14:11 UTC
I have a javascript file that looks like this, named test.js:

```
/******/ function testRails() {
/******/ }
```

When that file goes through sprockets in development, it gets a newline after the first comment:

```
/******/
 function testRails() {
/******/ }
```

This is just a sample file but it looks like the files I get from Webpack.  I build up an app/assets/javascripts/bundle.js file from Webpack, and then include that file in application.js, so the webpack built JS goes into the standard Rails bundle.

The extra newlines are breaking the Webpack sourcemaps.  (Note that I'm talking about Webpack sourcemaps, not Sprockets source maps.)

I tried this on 4.0.0beta2 and 3.6.0, same behavior in both places.

Here is a short bit of ruby to reproduce, you need a file named 'test.js' that looks like my snippet above:

```
require 'sprockets'

e = Sprockets::Environment.new

e.append_path '.'
a = e.find_asset 'test.js'
puts a.source
```

**Comment by schneems** [comment] 2016-04-29 14:15
Can you attach a sample project that reproduces the problem?

**Comment by mulvaney** [comment] 2016-04-29 14:25
https://github.com/mulvaney/sprockets-example

**Comment by schneems** [comment] 2016-04-29 14:33
🚀  thanks! I'll be able to dig in after railsconf. Thanks for the report.

**Comment by repinel** [comment] 2016-05-05 23:59
@schneems It seems to be an issue around in the [directive_processor.rb](https://github.com/rails/sprockets/blob/9112007ad3c25264196773a92827caa4746df116/lib/sprockets/directive_processor.rb#L118). It gets a little confused on how to handle inline and block comments.

I'm working on a possible fix for this.

**Comment by michaelherold** [comment] 2016-05-12 19:07
I think @repinel's fix addresses this issue. I added my thoughts over there.

**Closed** 2016-06-08 18:19 UTC
