### ISSUE TITLE
starts_with? on nil since upgrade to Rails 4.2.4

### ISSUE THREAD

**Issue by burnt43** [rails/sprockets#149] opened 2015-10-15 20:34 UTC
I upgraded to the latest Rails (4.2.4) to to get the fix for the following issue https://github.com/rails/rails/issues/20489. 

I've been getting this error when trying to load a page from my application. It seems someone in the chain is calling split_subpath method with a  nil argument.

<pre>
I, [2015-10-15T16:10:45.432210 #4390]  INFO -- : NoMethodError
I, [2015-10-15T16:10:45.432266 #4390]  INFO -- : undefined method `start_with?' for nil:NilClass
I, [2015-10-15T16:10:45.432341 #4390]  INFO -- : /usr/local/lib/ruby/gems/1.9.1/gems/sprockets-3.4.0/lib/sprockets/path_utils.rb:111:in `split_subpath'
</pre>

I just hacked the method as below to have a new first line and this is working. I don't know if this is the correct solution or if sprockets is really at fault or something else that uses sprockets.

Note: I downgraded to Rails 4.2.3 (which has the fix for issue 20489 in rails repo) and I don't get this issue with sprockets.

```ruby
def split_subpath(path, subpath)
      return nil unless path && subpath
      return "" if path == subpath
      path = File.join(path, '')
      if subpath.start_with?(path)
        subpath[path.length..-1]
      else
        nil
      end
    end
```

**Comment by rafaelfranca** [comment] 2015-10-15 20:36
Can you please provide a sample application that reproduces the error?

**Comment by burnt43** [comment] 2015-10-15 20:39
@rafaelfranca I will try and reproduce this issue.

**Comment by jasnow** [comment] 2015-10-15 21:01
FYI: After early research, I found out that the problem is "problem with passing a regexpr to str method". Previous issues: https://github.com/rails/sprockets/issues/117 and https://github.com/rails/sprockets-rails/issues/269

**Comment by rafaelfranca** [comment] 2015-10-15 21:11
Closing in favor of #117

**Closed by rafaelfranca** 2015-10-15 21:11 UTC
