### ISSUE TITLE
Sprockets not finding assets

### ISSUE THREAD

**Issue by rafaelfranca** [rails/sprockets#169] opened 2015-11-23 17:47 UTC
_From @lomefin on August 28, 2015 4:27_

I've been using gem 'bootstrap-sass' for a long while and its working fine in development.

But when sending my project to heroku I get the following error:

Sprockets::FileNotFound: could not find file: /tmp/build_3e3448ca910de3d9d48c939b8083d132/vendor/bundle/ruby/2.2.0/gems/bootstrap-sass-3.3.5.1/assets/javascripts/bootstrap/affix.js

Using Ruby version: ruby-2.2.2

Installing sprockets 3.3.3
Using sprockets-rails 2.3.2

I removed the loading error writing my own content instead of using bootrstrap-sprockets file 

Bootstrap-sprocket file requires
//= require ./bootstrap/affix

I switched them to 
//= require bootstrap/affix

But I'm getting more and more errors in other parts of my code.

_Copied from original issue: sstephenson/sprockets#737_

**Comment by rafaelfranca** [comment] 2015-11-23 17:47
_From @schneems on August 28, 2015 17:16_

If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

Thanks for your issue. I'm bugfixing sprockets 3.3.3 right now, the fastest way to get this fixed would be if you provide me with a small project that reproduces this issue.

**Comment by rafaelfranca** [comment] 2015-12-08 05:13
Can you please provide a sample application that reproduces the error?

**Comment by pravi** [comment] 2016-01-03 07:02
@rafaelfranca rails-assets-favico.js fails with sprockets 3.3 (sprockets-rails 2.3.2) but worked with sprockets 2.12 (sprocket-rails 2.1.3)

You can reproduce this with this simple code

```
rails new foo
cd foo

cat >> app/assets/javascripts/application.js <<EOF
# =require favico.js
EOF

cat >> Gemfile <<EOF
source "https://rails-assets.org" do
        gem 'rails-assets-favico.js'
end
EOF

bundle install
bundle exec rake assets:precompile

```

**Comment by pravi** [comment] 2016-01-05 18:39
Sorry, this should be #75

**Comment by schneems** [comment] 2016-10-10 16:11
Still an issue

```
**Sprockets::FileNotFound: couldn't find file 'favico.js' with type 'application/javascript'
Checked in these paths:
  /Users/richardschneeman/Documents/projects/tmp/assets-blerg-169/foo/app/assets/config
  /Users/richardschneeman/Documents/projects/tmp/assets-blerg-169/foo/app/assets/images
  /Users/richardschneeman/Documents/projects/tmp/assets-blerg-169/foo/app/assets/javascripts
  /Users/richardschneeman/Documents/projects/tmp/assets-blerg-169/foo/app/assets/stylesheets
  /Users/richardschneeman/Documents/projects/tmp/assets-blerg-169/foo/vendor/assets/javascripts
  /Users/richardschneeman/Documents/projects/tmp/assets-blerg-169/foo/vendor/assets/stylesheets
```

**Comment by schneems** [comment] 2016-10-10 16:18
The issue still exists in sprockets 3 but is resolved in master, please use the Sprockets 4 beta. If you want to find and backport the fix in a PR, i'll be happy to merge

**Comment by schneems** [comment] 2016-10-10 16:23
And...because no one gave me an example app, i'm finding out that it is broken on Sprockets master, but there was an error with the bug repro instructions.

**Closed** 2017-11-16 21:26 UTC
