### ISSUE TITLE
Sassc/Scssc processors do not update imported files

### ISSUE THREAD

**Issue by dagi3d** [rails/sprockets#330] opened 2016-06-26 21:24 UTC
I was testing the new libsass integration and found the following issue:

Given the following stylesheets
application.scss
```
@import '_base';
```

_base.scss
```
body {
  background: lime;
}
```

asset_pipeline:
```
Sprockets::Helpers.configure do |config|
  require 'sprockets/sassc_processor'
  assets.register_transformer 'text/scss', 'text/css', Sprockets::ScsscProcessor.new
```

If I make any change in `_base.scss` using the Scssc processor, the styles are not updated. To make the application.scss be updated, I need to make a change on it so it is precompiled again with `_base.scss` as well.
If I just the default scss processor it works without any problem.

**Comment by schneems** [comment] 2016-06-27 15:16
I'm currently working on sassc support. There's some bugs. Right now i'm trying to get sassc-rails working with sprockets 4 https://github.com/sass/sassc-rails/pull/65 after that i'm looking to get the SasscProcessor working and then hopefully get sass-rails to auto default to sassc when it's present and Sprockets 4 is being used. I don't have a timeline for those fixes but that's the gameplan.

**Comment by schneems** [comment] 2016-06-27 15:17
Dupe of #329

**Closed** 2016-06-27 15:17 UTC
