### ISSUE TITLE
sprockets 3 doesn't work without CoffeeScript?

### ISSUE THREAD

**Issue by rafaelfranca** [rails/sprockets#183] opened 2015-11-23 17:51 UTC
_From @pmontrasio on May 3, 2015 11:4_

I have a Rails project in which I disabled CoffeeScript by commenting it out in the generated Gemfile (I'm not using CS, only plain JS).

I removed Gemfile.lock and run bundle to get new versions of all the gems today. Sprocket has been upgraded to 3.0.3 from 2.12.3. Unfortunately the application doesn't work anymore. This is the error I get when trying to load the home page.

```
LoadError in HomeController#index
cannot load such file -- coffee_script
Extracted source (around line #274):

272 def require(file)
273   result = false
274   load_dependency(file) { result = super }
275   result
276   end
277 end
                
Rails.root: /home/me/project
Application Trace | Framework Trace | Full Trace

activesupport (4.2.1) lib/active_support/dependencies.rb:274:in `require'
activesupport (4.2.1) lib/active_support/dependencies.rb:274:in `block in require'
activesupport (4.2.1) lib/active_support/dependencies.rb:240:in `load_dependency'
activesupport (4.2.1) lib/active_support/dependencies.rb:274:in `require'
sprockets (3.0.3) lib/sprockets/autoload/coffee_script.rb:1:in `<top (required)>'
sprockets (3.0.3) lib/sprockets/coffee_script_processor.rb:15:in `cache_key'
sprockets (3.0.3) lib/sprockets/coffee_script_processor.rb:20:in `call'
sprockets (3.0.3) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.0.3) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.0.3) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.0.3) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.0.3) lib/sprockets/loader.rb:87:in `load_asset_by_uri'
sprockets (3.0.3) lib/sprockets/loader.rb:45:in `block in load'
sprockets (3.0.3) lib/sprockets/loader.rb:157:in `fetch_asset_from_dependency_cache'
sprockets (3.0.3) lib/sprockets/loader.rb:38:in `load'
sprockets (3.0.3) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.0.3) lib/sprockets/cached_environment.rb:47:in `yield'
sprockets (3.0.3) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.0.3) lib/sprockets/bundle.rb:23:in `block in call'
sprockets (3.0.3) lib/sprockets/utils.rb:183:in `dfs'
sprockets (3.0.3) lib/sprockets/bundle.rb:24:in `call'
sprockets (3.0.3) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.0.3) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.0.3) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.0.3) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.0.3) lib/sprockets/loader.rb:87:in `load_asset_by_uri'
sprockets (3.0.3) lib/sprockets/loader.rb:45:in `block in load'
sprockets (3.0.3) lib/sprockets/loader.rb:157:in `fetch_asset_from_dependency_cache'
sprockets (3.0.3) lib/sprockets/loader.rb:38:in `load'
sprockets (3.0.3) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.0.3) lib/sprockets/cached_environment.rb:47:in `yield'
sprockets (3.0.3) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.0.3) lib/sprockets/base.rb:63:in `find_asset'
sprockets (3.0.3) lib/sprockets/environment.rb:30:in `find_asset'
sprockets (3.0.3) lib/sprockets/base.rb:89:in `[]'
sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:230:in `lookup_asset_for_path'
sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:138:in `block in javascript_include_tag'
sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:136:in `map'
sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:136:in `javascript_include_tag'
actionview (4.2.1) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.1) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.1) lib/action_view/template.rb:143:in `render'
actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (4.2.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (4.2.1) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (4.2.1) lib/action_view/rendering.rb:100:in `_render_template'
actionpack (4.2.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (4.2.1) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (4.2.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
actionpack (4.2.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
actionpack (4.2.1) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.2.1) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/me/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
activesupport (4.2.1) lib/active_support/callbacks.rb:313:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
route_translator (4.0.0) lib/route_translator/extensions/action_controller.rb:20:in `set_locale_from_url'
activesupport (4.2.1) lib/active_support/callbacks.rb:432:in `block in make_lambda'
activesupport (4.2.1) lib/active_support/callbacks.rb:312:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:312:in `block in halting'
activesupport (4.2.1) lib/active_support/callbacks.rb:497:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:497:in `block in around'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
omniauth (1.2.2) lib/omniauth/builder.rb:59:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.6.0) lib/rack/etag.rb:24:in `call'
rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.0) lib/rack/head.rb:13:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
better_errors (2.1.1) lib/better_errors/middleware.rb:59:in `call'
web-console (2.0.0.beta4) lib/action_dispatch/debug_exceptions.rb:18:in `middleware_call'
web-console (2.0.0.beta4) lib/action_dispatch/debug_exceptions.rb:13:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.0) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.0) lib/rack/lock.rb:17:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
railties (4.2.1) lib/rails/engine.rb:518:in `call'
railties (4.2.1) lib/rails/application.rb:164:in `call'
rack (1.6.0) lib/rack/lock.rb:17:in `call'
rack (1.6.0) lib/rack/content_length.rb:15:in `call'
rack (1.6.0) lib/rack/handler/webrick.rb:89:in `service'
/home/me/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/home/me/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/home/me/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

This error occurred while loading the following files:
   coffee_script

Request

Parameters:

None
```

If I add ```gem "sprockets", "2.12.3"``` to the ```Gemfile``` it works again.

Does version 3 make some hard assumption on the presence of CoffeeScript?

_Copied from original issue: sstephenson/sprockets#724_

**Comment by rafaelfranca** [comment] 2015-11-23 17:51
_From @schneems on August 28, 2015 17:22_

If this is still an active issue can you close this one and re-open it at http://github.com/rails/sprockets. Active development has moved to that repo.

If you've got a bug with sprockets 3 please make sure you've tried the latest 3.3.3. If you can confirm this is still an active issue, the fastest way to get it fixed is to create a small example app that reproduces the failure and open an issue in the new repo http://github.com/rails/sprockets.

**Comment by rafaelfranca** [comment] 2015-11-23 17:51
_From @benpickles on September 7, 2015 16:53_

I have also encountered this but have tracked it down to the `teaspoon-jasmine` gem. Are you also using this @pmontrasio?

**Comment by rafaelfranca** [comment] 2015-11-23 17:51
_From @pmontrasio on September 8, 2015 6:51_

@benpickles I checked and I'm not using that gem.

@schneems I'll check with the new version as soon as I resume working on that project. I'll open an issue in its repository if I run again into that problem.

Thanks to both of you.

**Comment by rafaelfranca** [comment] 2015-11-23 17:51
_From @benpickles on September 8, 2015 10:42_

FYI I've created an issue in the Teaspoon repo for this: https://github.com/modeset/teaspoon/issues/405

**Comment by rafaelfranca** [comment] 2015-11-23 17:52
_From @benpickles on September 8, 2015 10:43_

Either way, in my case at least, the problem resides in another library and not Sprockets.

**Comment by arthurnn** [comment] 2015-11-28 16:48
@pmontrasio can you create an app that simulates the problem?

thanks

**Comment by ordinaryzelig** [comment] 2015-12-02 15:37
I just started getting this error as well. At first we weren't using the coffee_script gem, then I decided to use it. Everything was fine. Then we were having trouble with it, so we removed it again and converted the tiny coffeescript we had back to plain JS. There is no sign of any `.coffee` file anywhere except for git. Then we started getting this error too.

We're using sprockets 3.4.0. Will investigate more.

**Comment by ordinaryzelig** [comment] 2015-12-02 15:40
It's the cache. `rake tmp:cache:clear`.

**Comment by slumos** [comment] 2015-12-05 06:26
@ordinaryzelig: Thanks! That wfm.

**Comment by ordinaryzelig** [comment] 2015-12-05 14:54
> It's the cache. rake tmp:cache:clear.

Just an explanation of what I think is happening in case it helps. When you have coffeescript in the pipeline, it may be cached. Once you remove the coffeescript file and the gem, the residual cache stays because sprockets only overrides files that have changed, but doesn't clean up files from the cache that it doesn't see. The pipeline will read from the cache. When it sees the coffeescript file, it attempts to render it. And because it's a coffeescript file, it requires the coffee_script gem, doesn't find it, kaboom.

**Comment by rafaelfranca** [comment] 2015-12-08 03:16
Ok, that make sense. I can't think in a good way to detect that a gem that has influence in the sprockets cache was removed so I don't think there is any way to fix this issue. Maybe we could rescue load error and invalidate the cache?

**Comment by ordinaryzelig** [comment] 2015-12-08 03:22
Is it possible to detect something that is cached but shouldn't exist such as in this situation?

**Comment by rafaelfranca** [comment] 2015-12-08 03:59
It is not. The cache only know about the objects that it can reach.

**Comment by ordinaryzelig** [comment] 2015-12-08 05:44
I'm not familiar with the caching system. When you say "invalidate the cache", do you mean invalidating (deleting?) that single cached asset or clearing the entire cache and compiling the entire environment again?

Is it possible to know the difference between a load error similar to this situation vs a legit "oops, forgot to include the gem" situation?

**Comment by rafaelfranca** [comment] 2015-12-08 05:47
Clearing the entire cache and compiling the entire environment again.

> Is it possible to know the difference between a load error similar to this situation vs a legit "oops, forgot to include the gem" situation?

I don't think so.

**Comment by ordinaryzelig** [comment] 2015-12-08 05:58
> Clearing the entire cache and compiling the entire environment again.

So rescue load error, invalidate, compile again, retry? If load error happens again, then raise?

**Comment by schneems** [comment] 2015-12-08 17:00
I do want to add some better debugging for cases where you've used syntax and forgotten to add an extension for example if you have a `thing.js` and you do something like

```
var foo = <%= asset_path("foo.png") %>
```

It will error with a cryptic message because you aren't using the `erb` preprocessor.

We should also extend the error messages to point out when a file is errored that is using extensions that haven't been registered.

## This error

I'm not 100% clear on the error condition here.

It sounds like what is happening is that we have a `foo.js.coffee` file. We compile that with coffee script, which generates a file `foo.js` and cache entries. Maybe this file depends on other files also compiled with coffee script. Then coffee script is removed the filename changed to `foo.js` or maybe one of the dependencies is changed to not use coffee script. Then sprockets loads something from cache that is marked as being compiled with coffee_script that it needs to re-run through a preprocessor. When this happens it fails because coffee script gem is not available. 

There's a lot of  guesses and assumptions there ^^ without a working repro project it is hard for me to see if we could mitigate this problem somehow or raise a more meaningful error message. Does anyone have a simple project that reproduces the problem every time? Compile, remove gem, compile => error?

**Comment by ordinaryzelig** [comment] 2015-12-08 17:02
Unless someone beats me, I can make an example repo. I suspect it's dead easy to reproduce with a bare new rails app and following the steps you described.

**Comment by ordinaryzelig** [comment] 2015-12-09 03:11
https://github.com/ordinaryzelig/sprockets_stale_cache_app

Instructions in README.

**Comment by 3den** [comment] 2016-04-07 04:02
I have the same problem, adding `coffee-rails` gem fixes the issue but it sucks that we need coffeescript

**Comment by rafaelfranca** [comment] 2016-04-07 04:43
@3den you don't. Clear the cache and it will work without coffee-script. Please read the comments in this thread.

**Comment by 3den** [comment] 2016-04-07 19:26
@rafaelfranca I tried `rails tmp:clear`, `rails tmp:sockets:clear` and `rails tmp:cache:clear`... Even after that it fails because of coffescript.

**Comment by rafaelfranca** [comment] 2016-04-07 19:27
Can you please provide a sample application that reproduces the error?

**Comment by dreyks** [comment] 2016-05-06 10:23
Rails5 uses coffeescript now, namely `rails/actioncable/app/assets/javascripts/action_cable/connection.coffee`

If you encountered this error during rails 5 migration attempt (as I did) this is your cause

So, no, Sprockets does not require coffee-rails, rails5 itself requires it

**Comment by yairgo** [comment] 2016-06-15 17:55
@rafaelfranca , the example repo that @ordinaryzelig provided removed turbolinks, but it did not remove coffee-rails from the Gemfile. I am currently trying to reproduce a bug with teaspoon and I can't get a basic rails app to run with because of this issue(or something else weird that I did :( )

https://github.com/ordinaryzelig/sprockets_stale_cache_app/blob/master/Gemfile#L13

I'm creating an example repo now.

**Comment by ordinaryzelig** [comment] 2016-06-15 17:57
Been a while, but I believe the gem is still there to generate the cached files in the first place. And if you follow the instructions in the README, then you will get the error.

**Comment by yairgo** [comment] 2016-06-15 18:07
@ordinaryzelig MY BAD, you left coffee-rails in the Gemfile on purpose to show that it works with coffee rails in the Gemfile but does not work if you remove it. I didn't realize that at first.

**Comment by prathamesh-sonpatki** [comment] 2016-06-30 03:36
@rafaelfranca Here is a sample application https://github.com/prathamesh-sonpatki/final-demo-app

Steps to reproduce -

rails new demo
rails g scaffold Post name:string
rails db:migrate
rails s
visit /posts
stop server
remove coffee-rails from Gemfile
bundle
rake tmp:cache:clear
rails s
/posts throws an error - 
![monosnap 2016-06-30 09-05-37](https://cloud.githubusercontent.com/assets/621238/16476128/d6f37df4-3ea1-11e6-903b-2dfad14ad248.jpg)

Offending line - https://github.com/rails/sprockets/blob/f6295e0e0c9c460cfa61679b011c10ae7c975476/lib/sprockets/autoload/coffee_script.rb#L2

**Comment by vipulnsward** [comment] 2016-06-30 04:36
@prathamesh-sonpatki that App is failing because you still have a coffee file in path which leads sprockets to try and resolve coffeescript
https://github.com/prathamesh-sonpatki/final-demo-app/blob/master/app/assets/javascripts/posts.coffee 
Works when it is removed.

**Comment by prathamesh-sonpatki** [comment] 2016-06-30 04:42
Great! Indeed works fine 😀

**Comment by schneems** [comment] 2016-06-30 15:50
Great! So we can close this issue? Maybe we can have a better error? 

```
Tried to load file with `#{ extension }` extension #{ path } but you do not have `#{ gem }` loaded.
```

**Closed** 2016-07-01 16:33 UTC

**Comment by jejacks0n** [comment] 2016-07-28 21:28
So the solution for Teaspoon is to remove all .coffee files from asset paths, *even though* those coffee files are never required or referenced? This is what I'm seeing as I debug the issue.

**Comment by marckohlbrugge** [comment] 2019-07-21 00:59
Has anyone figured out a reliable way to figure out which dependency can cause this issue?

After completely removing coffeescript from my codebase, I get this same error. It's not a caching issue (cleared everything), so it's likely one of my Gemfile or Yarn dependencies. Would be great if there was a structured approach to tackling this. Unfortunately the stack trace is not much help. (it just leads to sprockets trying to require `coffee_script`).

**Comment by jonathanhefner** [comment] 2019-09-25 20:08
@marckohlbrugge Do you have `require rails-ujs` in your "application.js"?  `rails-ujs` is written in CoffeeScript, and might be triggering the error you see.

This was the case for me, in a test dummy app that otherwise had no CoffeeScript.  Clearing the cache worked temporarily, but the problem would resurface after testing against different versions of Rails.  The only solution was to add `gem "coffee-script"` to the Gemfile.

**Comment by marckohlbrugge** [comment] 2019-09-25 21:22
@jonathanhefner I forgot the specifics but there was indeed a node module that was written in coffee script. After updating all packages I was able to remove the coffee script gem without problems.

**Comment by marckohlbrugge** [comment] 2020-10-25 20:51
I just ran into this same issue again, but this time needed a different fix to clear the Heroku build cache:
https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache
