### ISSUE TITLE
Sprockets is raising Sprockets::FileNotFound for image assets that do exist 

### ISSUE THREAD

**Issue by mikeycgto** [rails/sprockets#451] opened 2017-01-10 15:45 UTC
### Expected behavior

Assets should compile successfully.

### Actual behavior

Assets are failing to compile on Heroku due to a `Sprockets::FileNotFound` error being raised. This seems to only happen on Heroku and does not happen locally (even when run locally with the staging or production environments set).

It only ever fails with images. Here is what our manifest.js looks like regarding images:

```js
//= link_tree ./../images .gif
//= link_tree ./../images .jpg
//= link_tree ./../images .jpeg
//= link_tree ./../images .png
```

This sort of error was sporadically happening last week with it failing to find 2 different image files that were not used in any SCSS (they were old images). Removing the image files seemed to remedy the problem and precompiling worked for dozens of subsequent builds. Changes within these subsequent builds included changes to both assets and unrelated application code.

For his particular error, the image is used in our SCSS so removing it is not an option. It's almost like once an asset file is not found during precompile, all subsequent deploys will continue to fail until we remove the image file.

I wonder if caching has something to do with it? Is there a way to disable caching entirely for the precompile process? We are not setting any cache options explicitly and I believe the Null cache store is being used but maybe I am wrong...

### System configuration

- sprockets-d22a4ea9c226 (current master)
- Ruby version 2.3.3

### Backtrace

```
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        Sprockets::FileNotFound: could not find file: /tmp/build_e296f6ae4c88324c54640ff593770ab9/app/assets/images/lightbox-spinner.gif
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/loader.rb:102:in `load_from_unloaded'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/loader.rb:59:in `block in load'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/loader.rb:43:in `load'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/cached_environment.rb:44:in `load'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/bundle.rb:32:in `block in call'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/bundle.rb:31:in `call'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/processor_utils.rb:84:in `call_processor'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/processor_utils.rb:65:in `reverse_each'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/processor_utils.rb:65:in `call_processors'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/loader.rb:144:in `load_from_unloaded'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/loader.rb:59:in `block in load'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/loader.rb:43:in `load'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/cached_environment.rb:44:in `load'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/base.rb:69:in `find_asset'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/base.rb:76:in `find_all_linked_assets'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/manifest.rb:124:in `block in find'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/manifest.rb:123:in `each'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/manifest.rb:123:in `find'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/sprockets/manifest.rb:165:in `compile'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets-5f525cd589f8/lib/rake/sprocketstask.rb:148:in `with_logger'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/gems/airbrake-5.6.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
remote:        /tmp/build_2f0fd9dfd7094d9363b61deccaaa6e1f/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
```

**Comment by schneems** [comment] 2017-01-10 16:04
Can you give me an app that reproduces the behavior?

**Comment by mikeycgto** [comment] 2017-01-10 16:12
Bumping `config.assets.version` in the Rails environment seemed to fix the issue. I wonder if its something with Heroku?

**Comment by mikeycgto** [comment] 2017-01-10 16:13
@schneems this is for our product SimplyBuilt, so unfortunately I cannot share the source :(

**Comment by schneems** [comment] 2017-01-10 16:16
I can't do much without an example repo. You can try to reproduce the problem with a simple app, it doesn't have to be __your__ app, just extract out the problem to a new repo. Replace sensitive images or logic with generic ones. 

I also work for Heroku, so I can tell you if that's the issue. It's likely a problem with sprockets (of which i'm a maintainer). Need to reproduce the bug first though.

**Comment by mikeycgto** [comment] 2017-01-10 16:16
@schneems let me see if I can put together a sample Rails app and get it deploying to Heroku that reproduces this problem.

I understand what I am reporting here is extremely strange. It is very perplexing to us as well but we are committed to getting to the bottom of it!

**Comment by mikeycgto** [comment] 2017-01-10 17:37
Unfortunately, I haven't been able to create a sample application that reproduces this problem. I tried creating a new Rails app with a bunch of image assets and some CSS. After many minor changes and deploys no `Sprockets::FileNotFound` exceptions were raised and all the builds completed without issue.

As I mentioned above, bumping asset versions may be a possible workaround for us when this issue occurs on deploys.

In the meanwhile, I setup our app to use a fork of Sprockets (https://github.com/SimplyBuilt/sprockets/commit/23bf1d121b670173837676df809f56f51076a564). This fork will print out some additional information from the file system and will hopefully help us get to the bottom of this problem we keep sporadically seeing.

Thanks for your help so far though @schneems!

**Comment by mikeycgto** [comment] 2017-01-10 22:04
It happened again on another deploy. Here our the results of our "hacky logs" branch from the sprockets fork:

```
remote:        Running: rake assets:precompile
remote:        FileNotFound: /tmp/build_ba746a321bd4351ce303816e0f620fe6/app/assets/images/lightbox-spinner.gif
remote:        ls: cannot access /tmp/build_ba746a321bd4351ce303816e0f620fe6/app/assets/images: No such file or directory
remote:        rake aborted!
remote:        Sprockets::FileNotFound: could not find file: /tmp/build_ba746a321bd4351ce303816e0f620fe6/app/assets/images/lightbox-spinner.gif
```

Rather strange that the app/assets/images directory is not available. We added more `ls` calls and logging to further examine the problem.

Once again bumping asset versions resolved the issue. Unfortunately this was on our production environment so I couldn't try this again with the additional logging from our fork.

**Comment by schneems** [comment] 2017-01-12 20:43
I really can't help unless I can reproduce the behavior myself. 

One guess is that every Heroku deploy happens at a different directory, maybe it's trying to load a file with a full path from the cache and the path is different.

**Comment by mikeycgto** [comment] 2017-01-13 16:56
Totally understand the need to reproduce this issue. It's very sporadic and seemingly random for us, so even reproducing it on our end is difficult.

Your suggestion sounds like it could explain this behavior. For whatever reason, Sprocket is trying to read files from paths that do not exist.

Feel free to close this issue in the meanwhile. I'm going to keep trying to get to the bottom of this and can reopen this issue when I have something more concrete to offer.

**Comment by mikeycgto** [comment] 2017-01-17 21:45
With more logging we're able to see the paths are definitely different. Here is the exception raised:

```
Sprockets::FileNotFound: could not find file: /tmp/build_5c2a0b57b0a1c5e58a21b7ecff2f8943/app/assets/images/lightbox-spinner.gif
```

Meanwhile, if we `ls` the `/tmp` directory, we can see the build directory is actually:

```
remote:        drwx------ 16 u51893 dyno     4096 Jan 17 19:11 build_f32ed12e1634ed1acad94614e50c2cb0
```

With some more logging, I can see all the `uri`'s passed to `Loader#load`: 

```
remote:        Loader#load "file:///tmp/build_18151a39ba9fdcf8a48bdf5f51291a1e/app/assets/config/manifest.js?type=application/javascript"
remote:        Loader#load "file:///tmp/build_18151a39ba9fdcf8a48bdf5f51291a1e/app/assets/config/manifest.js?type=application/javascript&pipeline=self"
remote:        Loader#load "file:///tmp/build_5c2a0b57b0a1c5e58a21b7ecff2f8943/app/assets/images/lightbox-spinner.gif?type=image/gif"
```

Digging a little deeper I see that all the images in the `to_load` Set from the primary asset's metadata in [lib/sprockets/bundle](https://github.com/rails/sprockets/blob/master/lib/sprockets/bundle.rb#L28) contain the incorrect build path.

```
remote:        #<Set: {"file:///tmp/build_5c2a0b57b0a1c5e58a21b7ecff2f8943/app/assets/images/lightbox-spinner.gif?type=image/gif", "file:///tmp/build_5c2a0b57b0a1c5e58a21b7ecff2f8943/app/assets/images/simon-gears.gif?type=image/gif", ... }>
```

We were able to repeatedly deploy changes to our sprockets fork to try to debug this issue. Modifying an asset this time (as we needed to fix a bug) fixed the compilation process and builds are now compiling successfully. When the builds are successful all our logging shows the correct `/tmp/build_` path for `uri`'s passed to `Loader#load`.

Any suggestions on why the paths may be wrong and where I should look? Is data cached on Heroku and used on subsequent builds?

**Comment by mikeycgto** [comment] 2017-01-19 17:34
Another workaround we've found when this issue arises is to run `heroku repo:purge_cache` from the heroku-repo plugin to clear the cache on Heroku. Deploys then succeed and assets compile successfully. That being said, we'll deploy once and then the next deploy will trigger this issue again.

Definitely seems to be something with the cache and incorrect roots.

**Comment by schneems** [comment] 2017-01-19 17:51
You can add a random value to your asset cache. This will cause cache invalidation every time you generate assets. Doesn't solve the root cause, which I can't help with without an example app...but it is better than manually clearing cache every time.

**Comment by mikeycgto** [comment] 2017-01-19 19:23
I can see that some of the .cache files (which are marshaled Ruby) have instance vars containing the incorrect root path. For example:

```
@fileI"l/tmp/build_1bd770480d4658f19c916f3d1f55668c/app/assets/stylesheets/themes/layout/main/_media_icons.scss;        T:@importero:Sass::Rails::SassImporte:
@rootI"c/tmp/build_1bd770480d4658f19c916f3d1f55668c/app/assets/stylesheets/themes/_theme00/layout.scss; F:@real_rootI"c/tmp/build_1bd770480d4658f19c916f3d1f55668c/app/assets/stylesheets/themes/_theme00/layout.sc
ss;
```

From this I get the sense that using scss `@import`s could potentially be to blame here. I'm going to keep trying to create an example app that reproduces this.

**Comment by schneems** [comment] 2017-01-19 23:07
make sure your sass and sass-rails are using the latest gems

**Comment by mattiasottosson** [comment] 2017-02-17 09:06
Just wanted to say that we have the exact same issue on our end (only happens on Heroku) 
Running precompilation locally in production env works just fine.

**Comment by dimroc** [comment] 2017-03-07 22:18
I'm currently having this happen w javascript assets as well. Specifically, application.js in the manifest.js file below:

```
// My images folder is actually empty except for .keep.
//= link_tree ../images

//= link application.js
//= link client.js

//= link admin.css
//= link application.css
//= link dealership.css
```

I suspect it has something to do with `link_tree` so I've moved that line to the bottom, and have since had success on heroku. But maybe the bug is spurious and it's just waiting to break again.

```
//= link application.js
//= link client.js

//= link admin.css
//= link application.css
//= link dealership.css

//= link_tree ../images
```

**Comment by davebrace** [comment] 2017-03-09 18:13
I'm running into this as well, except only on deploys to EngineYard. It definitely appears to be caching related - the error in our case seems to be that sprockets is trying to load a file from a previous deploy.  For example:

```
/data/app/releases/20170308202455/app/assets/images/nested-folder/ failing-image.eps is no longer under a load path: /data/app/releases/20170309174636/app/assets/images/, ...
```

One thing I noticed is that we're using `link_tree` and the specific nested-folder is not listed as a load path. I'm not sure if this matters since the parent directory is listed as a load path.

**Comment by miler350** [comment] 2017-10-07 00:19
It's a heroku issue according to this stackoverflow post: https://stackoverflow.com/questions/32209338/fails-to-push-to-heroku-sprocketsfilenotfound-could-not-find-application-css

I ran these commands to resolve the issue:
https://kb.heroku.com/how-do-i-clear-the-build-cache

**Comment by mollat** [comment] 2017-11-01 12:39
I had a similar issue without heroku. Just a plain nginx/puma setup. (Sprocket version is 3.7.1)

A quite simple app suddently stopped resolving new images under app/assets/images, even though assets:precompile was fine.

`2.4.0 :003 > ActionController::Base.helpers.asset_path('new-image.jpg')
Sprockets::Rails::Helper::AssetNotFound: The asset "new-image.jpg" is not present in the asset pipeline.`

This issue disappeared suddenly after changing `config.assets.version`. Hope the problem will never come back... ;)

**Comment by schneems** [comment] 2017-11-17 17:00
I really dislike spring.

**Closed by schneems** 2017-11-17 17:00 UTC

**Comment by maxhudson** [comment] 2017-12-20 20:07
`heroku config:set DISABLE_SPRING=1 -a <appname>` was the only thing that worked for me. Clearing build cache did not work.

**Comment by benoittgt** [comment] 2018-06-06 10:53
Hello

I'm having a similar issue. File is located in `assets/images/`. If I push to Heroku or if I run `$ bundle exec rake assets:precompile RAILS_ENV=production RAILS_GROUPS=assets` I have this error:

```
$ bundle exec rake assets:precompile RAILS_ENV=production RAILS_GROUPS=assets                     [12:48:17]
 rake aborted!
Sprockets::Rails::Helper::AssetNotFound: The asset "missing_screenshot.png" is not present in the asset pipeline.
/Users/bti/.rvm/gems/ruby-2.5.1@appaloosa/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:83:in `compute_asset_path'
/Users/bti/.rvm/gems/ruby-2.5.1@appaloosa/gems/actionview-5.1.6/lib/action_view/helpers/asset_url_helper.rb:198:in `asset_path'
/Users/bti/code/appaloosa/app/models/mobile_application_update.rb:25:in `<class:MobileApplicationUpdate>'
/Users/bti/code/appaloosa/app/models/mobile_application_update.rb:4:in `<main>'
/Users/bti/.rvm/gems/ruby-2.5.1@appaloosa/gems/bootsnap-1.1.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/bti/.rvm/gems/ruby-2.5.1@appaloosa/gems/bootsnap-1.1.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/bti/.rvm/gems/ruby-2.5.1@appaloosa/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/Users/bti/.rvm/gems/ruby-2.5.1@appaloosa/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/bti/.rvm/gems/ruby-2.5.1@appaloosa/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/Users/bti/.rvm/gems/ruby-2.5.1@appaloosa/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:379:in `block in require_or_load
...
```

The line that break is 
```ruby
  DEFAULT_IMAGE_PATH = ActionController::Base.helpers.asset_path('missing_screenshot.png')
```

I run and Heroku [cache command](https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache) and also change asset version ( `Rails.application.config.assets.version`).

Am I stupid?

**Comment by maxhudson** [comment] 2018-06-06 14:32
@benoittgt what's your rails version? and sprockets version?

**Comment by benoittgt** [comment] 2018-06-06 14:51
@maxhudson 
Rails 5.1.4
sprockets 3.7.1
sprockets-rails 3.2.1

**Comment by benoittgt** [comment] 2018-06-07 08:47
Ok we found the issue

in our model we have something like
```ruby
class User < ApplicationRecord
  CONSTANT = ActionController::Base.helpers.asset_path('missing_screenshot.png')
end
```

When you have no assets, no cache 
```
$ rm -rf public/assets
$ rm -rf tmp/cache
```
Any rake command like `rake assets:clobber` or  `rake assets:precompile` will load the constant and because you don't have the asset it will break.

Few options
- Don't use a call to `asset_path` when class are loaded before `assets` calls.
- set `config.assets.compile` to `true` (`# Do not fallback to assets pipeline if a precompiled asset is missed.`)

**Comment by schneems** [comment] 2018-06-07 13:11
For that code you can use a Proc or Lambda so that you only need the value when you’re actually using it.

I wouldn’t recommend using config.assets.compile in production. It’s very slow.

**Comment by diegodurante** [comment] 2021-11-11 16:45
> I wouldn’t recommend using config.assets.compile in production. It’s very slow.
👍  I agree, it is a bad idea, see [config.assets.compile=true in Rails production, why not?](https://stackoverflow.com/questions/8821864/config-assets-compile-true-in-rails-production-why-not)

> For that code you can use a Proc or Lambda so that you only need the value when you’re actually using it.
...

> Any rake command like RAILS_ENV=production rake assets:clobber or RAILS_ENV=production rake assets:precompile will load the constant and because you don't have the asset it will break.

This was exactly my case and your suggestion helped me to fix the issue! 🥳

In my case I started facing this issue while upgrading to Rails v5.2
Stack:
- Ruby 2.6.0
- Rails 5.2.6
- sprockets 4.0.2
- sprockets-rails 3.2.2

Command executed into a Dockerfile with:
````
RUN DB_ADAPTER=nulldb REDIS_HOST=localhost DEVISE_SECRET_KEY=dummy SECRET_KEY_BASE=dummy RAILS_ENV=staging bundle exec rails assets:precompile
````

At the end I was able to fix the issue with this diff:
BEFORE 🔴 
````ruby
has_attached_file :unprocessed_content, preserve_files: true, default_url:  ActionController::Base.helpers.asset_url('missing-image.png')
````

AFTER ✅ 
````ruby
has_attached_file :unprocessed_content, preserve_files: true, default_url: proc { ActionController::Base.helpers.asset_url('missing-image.png') }
````

So using proc 😉
